#!/bin/bash
export LOCATION="leonardo"
export RUN=srun
export UCX_IB_SL=1
export PARTITION="boost_usr_prod"
export COMPILE_ONLY="no"
export DEBUG_MODE="no"
export DRY_RUN="no"
export DELETE="yes"
export COMPRESS="yes"
export N_NODES=4
export OUTPUT_LEVEL="statistics"
export TEST_TIME="01:00:00"
export TYPES="int32"
export SIZES="8,64,512,4096,32768,262144,2097152,16777216,134217728"
export SEGMENT_SIZES="0,16384,131072,1048576"
export MPI_LIB="OMPI"
export BINECC="mpicc"
export MPI_LIB_VERSION="4.1.6"
export TASKS_PER_NODE="1"
export GPU_PER_NODE="0"
export GPU_AWARENESS="no"
export MODULES="openmpi/4.1.6--gcc--12.2.0,python/3.11.6--gcc--8.5.0"
export COLLECTIVES="allgather,allreduce"
export ALLGATHER_ALGORITHMS="default_ompi,linear_ompi,k_bruck_ompi,recursive_doubling_ompi,ring_ompi,neighbor_ompi,sparbit_over,bine_block_by_block_over,bine_permute_remap_over,bine_send_remap_over,bine_2_blocks_over"
export ALLGATHER_ALGORITHMS_SKIP="default_ompi,linear_ompi,k_bruck_ompi,recursive_doubling_ompi,ring_ompi,neighbor_ompi,sparbit_over,bine_block_by_block_over,bine_permute_remap_over,bine_send_remap_over,bine_2_blocks_over"
export ALLGATHER_ALGORITHMS_SEGMENTED=(no no no no no no no no no no no)
export ALLREDUCE_ALGORITHMS="default_ompi,recursive_doubling_ompi,ring_ompi,ring_segmented_ompi,rabenseifner_ompi,bine_lat_over,bine_bdw_remap_over,bine_bdw_remap_segmented_over"
export ALLREDUCE_ALGORITHMS_SKIP="ring_ompi,ring_segmented_ompi,rabenseifner_ompi,bine_bdw_remap_over,bine_bdw_remap_segmented_over"
export ALLREDUCE_ALGORITHMS_SEGMENTED=(no no no yes no no no no)
